# Generated by Django 5.2.7 on 2025-10-11 17:54

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(help_text='Formato: +573XXXXXXXXX o 3XXXXXXXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe ser válido (formato colombiano)', regex='^(\\+57|57)?[3][0-9]{9}$')])),
                ('tipo_usuario', models.CharField(choices=[('campesino', 'Campesino'), ('comprador', 'Comprador')], default='campesino', max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='avatars/')),
                ('calificacion_promedio', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Calificación promedio del usuario', max_digits=2)),
                ('total_calificaciones', models.PositiveIntegerField(default=0, help_text='Número total de calificaciones recibidas')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'indexes': [models.Index(fields=['email'], name='users_usuar_email_af433f_idx'), models.Index(fields=['tipo_usuario'], name='users_usuar_tipo_us_8e6b94_idx'), models.Index(fields=['estado'], name='users_usuar_estado_4bd86d_idx')],
            },
        ),
    ]
