# Generated by Django 5.2.7 on 2025-10-11 19:18

import utils.file_handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario (máx. 5MB, formatos: JPG, PNG, GIF, WebP)', null=True, upload_to=utils.file_handlers.ImageUploadHandler('users/profiles'), validators=[utils.file_handlers.validate_image_file]),
        ),
    ]
