# Generated by Django 5.2.7 on 2025-10-13 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(help_text='Formato: 10 dígitos (ej: 3001234567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe tener 10 dígitos (formato colombiano)', regex='^(\\+57|57)?[0-9]{10}$')]),
        ),
    ]
