# Generated by Django 5.2.7 on 2026-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección obligatoria para compradores (Opcional para Campesinos)', max_length=255),
        ),
    ]
