# Generated by Django 5.2.7 on 2026-03-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_2fa',
            field=models.CharField(blank=True, help_text='Emoji secreto para Autenticación Basada en Reconocimiento (2FA)', max_length=50, null=True),
        ),
    ]
