# Generated by Django 5.2.7 on 2026-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usuario_imagen_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_2fa_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora hasta la que está bloqueado el 2FA por intentos excesivos', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_2fa_fallidos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Contador de intentos fallidos del PIN Visual'),
        ),
    ]
