# Generated by Django 5.2.7 on 2026-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_bloqueado_2fa_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_password_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora hasta la que está bloqueada la cuenta por contraseña incorrecta repetida', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_password_fallidos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Contador de intentos fallidos de contraseña'),
        ),
    ]
