# Generated by Django 5.2.7 on 2026-04-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuario_bloqueado_password_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suspendido_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora hasta la cual el usuario está sancionado. Si es nulo y el estado es Suspendido, es permanente.', null=True),
        ),
    ]
