# Generated by Django 5.2.7 on 2026-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usuario_suspendido_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin_recovery_code',
            field=models.CharField(blank=True, help_text='Código temporal de 6 dígitos para recuperar el PIN Visual', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pin_recovery_expires',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de expiración del código de recuperación', null=True),
        ),
    ]
