# Generated by Django 5.2.7 on 2025-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('entidad_certificadora', models.CharField(blank=True, max_length=150)),
                ('fecha_obtencion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('en_proceso', 'En Proceso')], default='vigente', max_length=11)),
                ('archivo_certificado', models.FileField(blank=True, help_text='Archivo digital del certificado', null=True, upload_to='certificados/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(max_length=150)),
                ('ubicacion_departamento', models.CharField(max_length=100)),
                ('ubicacion_municipio', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('area_hectareas', models.DecimalField(decimal_places=2, help_text='Área de la finca en hectáreas', max_digits=10)),
                ('tipo_cultivo', models.CharField(choices=[('organico', 'Orgánico'), ('tradicional', 'Tradicional'), ('hidroponico', 'Hidropónico'), ('mixto', 'Mixto')], default='organico', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, help_text='Latitud GPS', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, help_text='Longitud GPS', max_digits=11, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('en_revision', 'En Revisión')], default='activa', max_length=11)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
            },
        ),
    ]
