# Generated by Django 5.2.7 on 2025-10-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'campesino'}, on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='farms.finca'),
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['usuario'], name='farms_finca_usuario_9dd18d_idx'),
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['ubicacion_departamento', 'ubicacion_municipio'], name='farms_finca_ubicaci_da8404_idx'),
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['estado'], name='farms_finca_estado_905aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacion',
            index=models.Index(fields=['finca'], name='farms_certi_finca_i_986faa_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacion',
            index=models.Index(fields=['estado'], name='farms_certi_estado_a286db_idx'),
        ),
    ]
