# Generated by Django 5.2.7 on 2026-03-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificacion',
        ),
    ]
