# Generated by Django 5.2.7 on 2025-10-11 17:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('campesino', models.ForeignKey(limit_choices_to={'tipo_usuario': 'campesino'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_campesino', to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'comprador'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_comprador', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='products.producto')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensaje', models.CharField(choices=[('texto', 'Texto'), ('oferta', 'Oferta de Precio'), ('negociacion', 'Negociación'), ('sistema', 'Mensaje del Sistema')], default='texto', max_length=12)),
                ('contenido', models.TextField()),
                ('precio_ofertado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad_ofertada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='anti_intermediarios.conversacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ReporteImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_transacciones', models.PositiveIntegerField(default=0)),
                ('ahorro_total_generado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('campesinos_beneficiados', models.PositiveIntegerField(default=0)),
                ('compradores_beneficiados', models.PositiveIntegerField(default=0)),
                ('productos_top', models.JSONField(blank=True, default=list)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de Impacto',
                'verbose_name_plural': 'Reportes de Impacto',
                'indexes': [models.Index(fields=['fecha_inicio', 'fecha_fin'], name='anti_interm_fecha_i_8b17c1_idx'), models.Index(fields=['fecha_generacion'], name='anti_interm_fecha_g_c1d901_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransparenciaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_campo_directo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_mercado_tradicional', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fuente_precio_referencia', models.CharField(default='SIPSA-DANE', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ciudad_referencia', models.CharField(blank=True, max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_precio', to='products.producto')),
            ],
            options={
                'verbose_name': 'Transparencia de Precios',
                'verbose_name_plural': 'Transparencia de Precios',
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['campesino'], name='anti_interm_campesi_493fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['comprador'], name='anti_interm_comprad_749654_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_actualizacion'], name='anti_interm_fecha_a_38599a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('campesino', 'comprador', 'producto')},
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion'], name='anti_interm_convers_aab85f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['fecha_envio'], name='anti_interm_fecha_e_9bafb6_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['leido'], name='anti_interm_leido_5fc1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transparenciaprecios',
            index=models.Index(fields=['producto'], name='anti_interm_product_0fe039_idx'),
        ),
        migrations.AddIndex(
            model_name='transparenciaprecios',
            index=models.Index(fields=['fecha_registro'], name='anti_interm_fecha_r_0cd54e_idx'),
        ),
    ]
