# Generated by Django 5.2.7 on 2025-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anti_intermediarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparenciaprecios',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
