# Generated by Django 5.2.7 on 2025-10-11 17:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(editable=False, help_text='Formato: ORD-XXXXX', max_length=20, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En Preparación'), ('ready', 'Listo para Entrega'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=15)),
                ('notas_comprador', models.TextField(blank=True)),
                ('notas_campesino', models.TextField(blank=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('fecha_entrega_programada', models.DateField(blank=True, null=True)),
                ('hora_entrega_programada', models.TimeField(blank=True, null=True)),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('calificacion_comprador', models.PositiveSmallIntegerField(blank=True, help_text='Calificación del comprador al campesino', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('calificacion_campesino', models.PositiveSmallIntegerField(blank=True, help_text='Calificación del campesino al comprador', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_calificacion', models.TextField(blank=True)),
                ('campesino', models.ForeignKey(limit_choices_to={'tipo_usuario': 'campesino'}, on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos_campesino', to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'comprador'}, on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos_comprador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad al momento del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('nombre_producto_snapshot', models.CharField(help_text='Nombre del producto al momento del pedido', max_length=150)),
                ('unidad_medida_snapshot', models.CharField(help_text='Unidad de medida al momento del pedido', max_length=7)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='products.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['comprador'], name='orders_pedi_comprad_ecefd1_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['campesino'], name='orders_pedi_campesi_f9594f_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='orders_pedi_estado_add46f_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='orders_pedi_fecha_p_ee8923_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['codigo_seguimiento'], name='orders_pedi_codigo__a0c93f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
