# Generated by Django 5.2.7 on 2026-04-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Screenshot del comprobante Nequi o transferencia bancaria', null=True, upload_to='comprobantes_pago/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='disputa_abierta',
            field=models.BooleanField(default=False, help_text='True si alguna de las partes reportó un problema con este pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_confirmacion_pago',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el campesino aceptó el comprobante', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_disputa',
            field=models.TextField(blank=True, help_text='Descripción del problema reportado por comprador o campesino'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_confirmado_campesino',
            field=models.BooleanField(default=False, help_text='El campesino confirmó haber recibido el pago antes de despachar'),
        ),
    ]
