# Generated by Django 5.2.7 on 2025-10-11 17:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='🌱', max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('gramo', 'Gramo'), ('unidad', 'Unidad'), ('libra', 'Libra'), ('arroba', 'Arroba')], default='kg', max_length=7)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('temporada', 'Fuera de Temporada'), ('inactivo', 'Inactivo')], default='disponible', max_length=10)),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/')),
                ('galeria_imagenes', models.JSONField(blank=True, default=list, help_text='Array de URLs de imágenes adicionales')),
                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por comas: orgánico, fresco, etc.', max_length=500)),
                ('calidad', models.CharField(choices=[('premium', 'Premium'), ('primera', 'Primera'), ('segunda', 'Segunda')], default='primera', max_length=8)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('peso_minimo_venta', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('peso_maximo_venta', models.DecimalField(decimal_places=2, default=Decimal('100.0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('disponible_entrega_inmediata', models.BooleanField(default=True, help_text='¿Está disponible para entrega inmediata?')),
                ('tiempo_preparacion_dias', models.PositiveIntegerField(default=1, help_text='Días necesarios para preparar el pedido', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoriaproducto')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='farms.finca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
