# Generated by Django 5.2.7 on 2025-10-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'campesino'}, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['usuario'], name='products_pr_usuario_ca940c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='products_pr_categor_729bab_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='products_pr_estado_d8eaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio_por_kg'], name='products_pr_precio__8c34d9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock_disponible'], name='products_pr_stock_d_231428_idx'),
        ),
    ]
