# Generated by Django 5.2.7 on 2026-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producto_imagen_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SipsaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=150)),
                ('producto', models.CharField(max_length=200)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_captura', models.DateTimeField(blank=True, null=True)),
                ('ultima_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio SIPSA',
                'verbose_name_plural': 'Precios SIPSA',
                'indexes': [models.Index(fields=['producto'], name='products_si_product_0cde3e_idx'), models.Index(fields=['ciudad'], name='products_si_ciudad_911b71_idx')],
                'unique_together': {('ciudad', 'producto')},
            },
        ),
    ]
