# Generated by Django 5.0 on 2026-04-07 02:06

from django.db import migrations

def poblar_categorias(apps, schema_editor):
    CategoriaProducto = apps.get_model('products', 'CategoriaProducto')
    
    categorias = [
        {'id': 10, 'nombre': 'Frutas', 'icono': '🍎'},
        {'id': 13, 'nombre': 'Vegetales y Hortalizas', 'icono': '🥬'},
        {'id': 14, 'nombre': 'Granos y Cereales', 'icono': '🌾'},
        {'id': 15, 'nombre': 'Hierbas Aromáticas', 'icono': '🌿'},
        {'id': 16, 'nombre': 'Tubérculos', 'icono': '🥔'},
        {'id': 17, 'nombre': 'Legumbres', 'icono': '🫘'},
    ]
    
    for cat_data in categorias:
        try:
            # Eliminar si existe con otro ID, para forzar el ID correcto
            if CategoriaProducto.objects.filter(nombre=cat_data['nombre']).exclude(id=cat_data['id']).exists():
                cat = CategoriaProducto.objects.get(nombre=cat_data['nombre'])
                # Solo borramos si no tiene productos asociados, si tiene productos lo ignoramos localmente.
                if cat.productos.count() == 0:
                    cat.delete()
                else:
                    # Renombrar temporalmente si está trabado
                    cat.nombre = cat.nombre + '_viejo'
                    cat.save()

            CategoriaProducto.objects.update_or_create(
                id=cat_data['id'],
                defaults={
                    'nombre': cat_data['nombre'],
                    'icono': cat_data['icono'],
                    'estado': 'activo',
                }
            )
        except Exception as e:
            print(f"Skipping category {cat_data['nombre']} due to local dev constraints: {e}")

def revertir_categorias(apps, schema_editor):
    CategoriaProducto = apps.get_model('products', 'CategoriaProducto')
    CategoriaProducto.objects.filter(id__in=[10, 13, 14, 15, 16, 17]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sipsaprecio'),
    ]

    operations = [
        migrations.RunPython(poblar_categorias, revertir_categorias),
    ]
