# Generated by Django 5.0 on 2026-04-07 02:12

from django.db import migrations

def poblar_nuevas_categorias(apps, schema_editor):
    CategoriaProducto = apps.get_model('products', 'CategoriaProducto')
    
    categorias = [
        {'id': 18, 'nombre': 'Productos Avícolas', 'icono': '🥚'},
        {'id': 19, 'nombre': 'Carnes y Pescados', 'icono': '🥩'},
        {'id': 20, 'nombre': 'Lácteos y Derivados', 'icono': '🥛'},
        {'id': 21, 'nombre': 'Plantas y Flores', 'icono': '🌻'},
        {'id': 22, 'nombre': 'Insumos Agrícolas', 'icono': '🚜'},
        {'id': 23, 'nombre': 'Miel y Procesados', 'icono': '🍯'},
    ]
    
    for cat_data in categorias:
        try:
            if CategoriaProducto.objects.filter(nombre=cat_data['nombre']).exclude(id=cat_data['id']).exists():
                cat = CategoriaProducto.objects.get(nombre=cat_data['nombre'])
                if cat.productos.count() == 0:
                    cat.delete()
                else:
                    cat.nombre = cat.nombre + '_viejo_2'
                    cat.save()

            CategoriaProducto.objects.update_or_create(
                id=cat_data['id'],
                defaults={
                    'nombre': cat_data['nombre'],
                    'icono': cat_data['icono'],
                    'estado': 'activo',
                }
            )
        except Exception as e:
            print(f"Skipping category {cat_data['nombre']} due to constraints: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_poblar_categorias'),
    ]

    operations = [
        migrations.RunPython(poblar_nuevas_categorias),
    ]
