# Generated by Django 5.2.7 on 2026-04-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_nuevas_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (Kg)'), ('libra', 'Libra'), ('arroba', 'Arroba'), ('gramo', 'Gramo'), ('bulto', 'Bulto'), ('caja', 'Caja'), ('canasta', 'Canasta'), ('unidad', 'Unidad (Ej: Pollo)')], default='kg', max_length=7),
        ),
    ]
